### ISSUE TITLE
Последний рывок

### ISSUE THREAD

**Issue by v-pereskokov** [DVI-GI-2017/Jira__backend#89]
- [x] Fix падения при получении тасков и проектов (всех)
- [x] Возможность создавать таск с пробелами в title

- [x] Получение тасков проекта

- [x] Получать таски вместе с пользователями, а не их id

**Comment by grim-yawn** [comment]
Таск с пробелами уже можно добавлять. Там правила на все title одинаковые.

**Comment by grim-yawn** [comment]
Только url для них:
/projects/:project_id/tasks
и в теле - таск (без project_id и id, т.к. всё равно перезаписываются)
